### ISSUE TITLE
countdown works locally, not on server

### ISSUE THREAD

**Issue by JoeriWissink** [chapkovski/custom-waiting-page-for-mturk#4]
Dear Philipp,

Really great custom wait page. However, it only works perfectly for me when I test it locally. When I try to run it on our university's test server the time out does not seem to work:

The otree-timer__time-left countdown doesn't show and the finish study button does not show up after the indicated time. Both show when testing locally.

Do you have any indication what I might be missing? Maybe some requirements the test-server might be missing to run the javascript code correctly?

Thanks in advance for your reply.

Joeri Wissink

**Comment by chapkovski** [comment]
hi Joeri,

what version of oTree do you use? (you can get it if you type `otree --version` in your server's console

**Comment by JoeriWissink** [comment]
Dear Philipp,

Thank you for your quick reply.

The test server uses 1.2.8, locally I use 1.8.8.

Best,
Joeri

**Comment by chapkovski** [comment]
I think you mixed up oTree version and Django version (which is 1.8.8 for all recent oTree versions apart from the most recent 1.5 Beta). But 1.2.8 on test server explains why the timer doesn't work: the name for oTree timer was changed starting from 1.3.9. I can adjust the code so it will work with older versions of oTree as well, but I **strongly** recommend to update oTree on your server instead - 1.2.8 is really an old one.

**Comment by JoeriWissink** [comment]
Updating the otree-core solved the issue. Thank you!
