### ISSUE TITLE
Games in Wait Room

### ISSUE THREAD

**Issue by DeFilippis** [chapkovski/custom-waiting-page-for-mturk#5]
Hey all,

In the ReadMe message, you have indicated that in the future you may support adding games (such as snake and tetris) to the waiting room.  Is there currently a beta implementation of these features I could use?  I anticipate having some mTurkers wait upwards of 10 minutes, and would like something to keep them occupied. 

Best

**Comment by ngruyer** [comment]
Hi Evan. 
Unfortunately, we do not have any beta implementation of this, yet.
Best
Nicolas
